var rule={
    title:'玩偶哥哥',
    模板:'AlistShare',
    host:'https://wogg.xyz',
    headers:{
        'Cookie':'_ga=GA1.1.1243752718.1703129426; cf_clearance=HH1VuOnnRcxUYXGl_CxM..G40hgaS0a26xpgh1HAGgM-1706421052-1-AR+Ty22GQ7MQMLHGm2LAcC7lzSmRLO+0a3JB80B21dwbkRyFm5Isyt7YNO7du2Nk66U2APFoC91lYxLKN6xLwy0=; closeclick=closeclick;',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
    },
    url:'/index.php/vodshow/fyclass--------fypage---.html',
    filterable:0,//是否启用分类筛选,
    filter_url:'',
    filter: {},
    searchUrl:'/index.php/vodsearch/**-------------.html',
    searchable:2,
    class_parse: 'ul.nav-menu-items&&li.nav-menu-item;a&&Text;a&&href;/(\\d+).html',
    推荐:'.module-list;.module-items&&.module-item;*;*;*;*',
    double:true,
    一级:'.module-list&&.module-items&&.module-item;.module-item-cover&&.module-item-pic&&a&&title;.module-item-cover&&.module-item-pic&&img&&data-src;.module-item-text&&Text;.module-item-cover&&.module-item-pic&&a&&href',
    二级:{
        "title": "h1&&Text;.video-info-aux a:eq(0)&&Text",
        "img": ".video-cover img&&data-src",
        "desc": ".module-row-title&&p&&Text;.video-info-main&&.video-info-item:eq(2) a&&Text;.video-info-aux a:eq(3)&&Text;.video-info-main&&.video-info-item:eq(1)&&Text;.video-info-main&&.video-info-item:eq(0)&&Text",
        "content": ".sqjj_a&&Text",
    },
    搜索:'.module-search-item;h3&&Text;*;.video-serial&&Text;.video-info-header&&h3&&a&&href',
}
